includes/class-scd-ext-access-control.php
includes/class-scd-ext-lesson-admin.php
includes/class-scd-ext-lesson-frontend.php
includes/class-scd-ext-quiz-frontend.php

Fixes https://github.com/woocommerce/sensei-content-drip/issues/103.

Fix time formatting by storing dates as unix timestamps in DB.

---

includes/class-scd-ext-lesson-frontend.php
includes/class-scd-ext-quiz-frontend.php

Don't show quiz content if lesson hasn't dripped
When visiting a quiz page:
- Don't show quiz content if it is part of a lesson that hasn't dripped yet.
- Display SCD Message if this Quiz is part of a lesson that has't
dripped yet.
NB: There was a hook that changed post content of quizzes but
those were never used in sensei templates.
closes #99
Steps to test:
- Create a course with two lessons, set the second one to drip.
- Add a quiz to the second lesson
- Try to access the quiz page. You see only the SCD notice and no quiz questions
- ON the lesson page, you do not see a button that gets you to the quiz

Don't show quiz/media content if lesson hasn't dripped

---

includes/class-scd-ext-access-control.php
includes/class-scd-ext-drip-email.php
includes/class-scd-ext-lesson-frontend.php
includes/class-scd-ext-quiz-frontend.php
includes/class-scd-ext-utilities.php

Fixes #75. For the 4 strings in Sensei -> Settings -> Content Drip, we now check:
1) String has an active translation? Use it.
2) No active translation, but has a value set under Sensei -> Settings -> Content Drip? Use it.
3) No active translation, or value set in Settings? Use default English string.
Created a `utils->check_for_translation()` function to store this logic.
Preliminary testing shows the fix works in all the above use cases, but additional testing / cleanup will be required.

Check for translations before defaulting to strings in Settings

---

assets/js/admin-lesson.js
includes/class-scd-ext-lesson-admin.php
includes/class-scd-ext-manual-drip.php

Fixes https://github.com/woocommerce/sensei-content-drip/issues/86.
The PR adds the following button to lessons Edit view:
After clicking the button, the user gets the following alert:
And the following e-mail:

Add the ability in lessons to send test emails

---

includes/class-scd-ext-drip-email.php
includes/class-scd-ext-settings.php

Fixes https://github.com/woocommerce/sensei-content-drip/issues/60.

Add the option to disable Email notifications in Settings.

---

includes/class-scd-ext-access-control.php
includes/class-scd-ext-lesson-frontend.php
includes/class-scd-ext-quiz-frontend.php
includes/class-scd-ext-settings.php

Fixes https://github.com/woocommerce/sensei-content-drip/issues/121
See the issue for an explanation of the bug.
This solution blocks access for both lessons and quizzes.
When trying to access a lesson or quiz whose content is not yet available, the error message specifies on which date the content will become available. However, when displaying the message for a user who has not started the course, this cannot be calculated for dynamic drip periods (i.e. drip periods that are a number of days after the course is started).
So for this case, we need to display a more generic message, simply saying that the lesson or quiz content is not available before starting the course. To remain consistent with the content that is already used, I added settings for customizing the new messages as well. …

Fix access to dripped lessons for users not taking the course

---

sensei-content-drip.php

Changed plugin author and URI for branding consistency

---

includes/class-scd-ext-lesson-admin.php

Fixes #124 
Note that I was not able to reproduce the fatal mentioned in that issue.
Also note that I built this on top of #146 in order to work with Sensei 2.0. I will rebase when #146 is merged.
See #124. Ensure content drip works.

Ensure HTML escaping only occurs for strings

---

sensei-content-drip.php

Fixes #91 
Schedules the cron job to run at 00:30 in the timezone set in the WordPress settings.
Note that I built this on top of #146 in order to work with Sensei 2.0. I will rebase when #146 is merged.
- Deactivate and reactivate the plugin.
- Inspect the cron jobs (the plugin [WP Crontrol](https://en-ca.wordpress.org/plugins/wp-crontrol/) is useful for this).
- Ensure the cron job `woo_scd_daily_cron_hook` is set to run tomorrow at 00:30 (12:30am) in the timezone configured in WordPress.
- In WordPress settings, change the timezone to one whose current date is different.
- Follow the steps above. Ensure the cron job is set to run on the following day at 00:30 relative to the configured timezone.

Ensure emails are sent at 00:30 in the WordPress-configured timezone

---

includes/class-scd-ext-lesson-admin.php

Closes #133 
This changes the date display for the Lessons table to match the format specified in the WordPress settings.
Note that it does not change the date format in the meta box, which was specified in #133. There are a few reasons for this:
- Since we are using a datepicker, the displayed format is probably not quite as important.
- We explicitly tell our users what format should be used in the input, and it is locale-independent.
- The available date format specifiers for the [datepicker](http://api.jqueryui.com/datepicker/#utility-formatDate) and the [WordPress setting](http://php.net/manual/en/function.date.php) do not match. It seems that it would be very difficult and error-prone to try to make the displayed format (which must work with the datepicker) exactly match the …

Use WordPress date format for Lesson table

---

includes/class-scd-ext-drip-email.php

Fixes https://github.com/woocommerce/sensei-content-drip/issues/134
See issue for testing instruction. This PR removes the PHP notice.

Fix PHP notice when array index does not exist

---

includes/class-scd-ext-drip-email.php
includes/class-sensei-content-drip.php
templates/single-email-drip-notification.php

Closes https://github.com/woocommerce/sensei-content-drip/issues/85
This PR extracts the rendering of the content drip email to a template file. It uses Sensei's template file loading so that the template may be overridden by the theme.
- Create a few courses with some lessons in each one.
- Set the Content Drip setting for the lessons to a "specific date" and set the date to today.
- Manually run the `woo_scd_daily_cron_hook` cron event (the "WP Crontrol" plugin is one way to do this).
- Ensure that the email is sent properly, and that it looks right. To verify, switch to the `master` branch, run the event again, and compare the email from the `master` branch with the email from this branch. They should be identical.
- Switch back to this branch before continuing.
- Reorder some dripped …

Extract email template to a template file

---

sensei-content-drip.php

Minor fix. In order to catch PHP 5.2, we need to delay using __DIR__ until a file loaded after the dependency checker.

Don't use newer __DIR__ until after dependency check

---

includes/class-scd-ext-access-control.php

See https://make.wordpress.org/core/2017/05/22/multisite-focused-changes-in-4-8/.
And https://core.trac.wordpress.org/ticket/39205#comment:13.
Introduced in WP 4.8, `upgrade_netrowk` is the new more granular
way to check for super_admins. Use it if the wp installation permits.

Support new Multisite Capabilities of WP 4.8

---

includes/class-scd-ext-dependency-checker.php
includes/class-sensei-content-drip.php
sensei-content-drip.php

This PR: 
- Changes _plugin_ dependency checks until after plugins are first loaded. (https://github.com/woocommerce/sensei-course-progress/pull/68#issuecomment-472816337)
- Refactors a bit to make the above possible and match our other plugins.
- Consolidates activation hooks and moves deactivation hook to match.
- Self-deactivate if system dependencies aren't met.
In addition to the comments in #68, this is also necessary because we don't set up our activation hooks if the plugin dependencies aren't met.
- If activated, deactivate all versions of Sensei. 
- Remove `sensei-version` and `woothemes-sensei-version` options.
- If not active, activate this plugin on built version of this branch. Verify the Sensei dependency message shows on Plugins page and Dashboard page.
- Activate Sensei …

Load plugin during `plugins_loaded`

---

includes/class-scd-ext-drip-email.php

`create_function()` was deprecated in PHP 7.2 and will be removed. This was really easy to replace.
To test, add multiple lessons to slow drip course that drop on the same day. Send a test email and verify no PHP warnings get logged.

Replace usage of `create_function()`

---

includes/class-scd-ext-dependency-checker.php
includes/class-sensei-content-drip.php

As I've been working through the other plugins, I've started loading the localizations and textdomain slightly earlier. I'd like to change this here for consistency. This should also allow our plugin dependency notice to be localized. Unfortunately, our PHP notice probably won't get localized.

Load text domain and localizations slightly earlier

---

includes/class-scd-ext-lesson-frontend.php
includes/class-sensei-content-drip.php

Fixes #139 
This change fixes the issue that lesson comments where visible although the lesson was not accessible due to content drip. It relies on the filter that was added with [this](https://github.com/Automattic/sensei/pull/2795) PR.
1. In Sensei settings, make sure that General->Access Permissions and Lessons->Allow Comments for Lessons are enabled.
2. Create a lesson and with a user add a comment to it.
3. By using content drip, make the lesson inaccessible by setting a future date that it will be accessible.
4. With another user subscribe to the course.
5. Open the lesson page and observe that the comments are not displayed.
6. Update the lesson again to make it accessible.
7. Check again and see that now the comments are displayed.
This change has a dependency on [this …

Add filter to hide comments when lesson is blocked

---

includes/class-scd-ext-drip-email.php

Fixes #154 
Lessons can be ordered by two separate ways, by module or by lesson.
Previously, the lessons in the emails were only ordered if a lesson order was
defined and the module ordering was ignored. This is now fixed. Course ordering is not considered since we have no pages that display lessons from different courses. However the lessons that belong to the same course will be listed together.
The automated tests for content drip are not configured to run at the moment. I spent some time trying to add a test and run it but unfortunately it proved to be a time consuming task so I skipped adding automated tests. 
Manual test cases that were executed:
- Ordering is correct when all lessons belong to a module.
- Ordering is correct when some lessons belong to modules.
- Ordering is …

Fix email lesson ordering

---

includes/class-scd-ext-access-control.php

Fixes #167 
Admin and teacher users were unable to view the content of lessons that haven't dripped.
The admin issue was introduced by https://github.com/woocommerce/sensei-content-drip/pull/127. `upgrade_network` is a multi-site only capability (https://wordpress.org/support/article/roles-and-capabilities/#upgrade_network). It was fixed adding an `is_multisite()` validation to the conditional.
For the teacher case, we updated checking if the user is a teacher and if they are the teacher on the specific lesson.
- Assign a drip schedule to a lesson that is some date in the future.
**Admin test**
- As an admin-level user, start taking the course that lesson is in.
- Browse to the lesson that hasn't dripped yet.
**Teacher test**
- Add a teacher to the course.
- Log in as the teacher.
- …

Fix dripped view capabilities for the content of the lessons

---

includes/class-scd-ext-lesson-frontend.php

Fixes #199
* Remove all actions from the `sensei_single_lesson_content_inside_before` and `sensei_single_lesson_content_inside_after` hooks if the lesson hasn't dripped yet. 
* Activate the Media attachments plugin and add attachments to a lesson.
* Set that lesson to be available in a future date in the Content Drip metabox.
* Start the course with a new user and open the lesson.
* Make sure no lesson content is visible, including the Lesson Media attached in the first step.

Disable all content hooks if lesson is not available

---

composer.json
composer.lock
includes/class-scd-ext-access-control.php
includes/class-scd-ext-dependency-checker.php
includes/class-scd-ext-drip-email.php
includes/class-scd-ext-lesson-admin.php
includes/class-scd-ext-lesson-frontend.php
includes/class-scd-ext-utilities.php
package.json
sensei-content-drip.php
tests/bootstrap.php
tests/framework/class-time-machine.php
tests/framework/drip-test-helpers.php
tests/unit-tests/test-class-scd-ext-access-control.php
tests/unit-tests/test-class-scd-ext-drip-email.php
tests/unit-tests/test-class-scd-ext-lesson-admin.php
tests/unit-tests/test-class-scd-ext-utils.php

Fixes #196
* Bumps WP minimum version to 5.3. This is in line with Sensei LMS and also saves lots of annoying compatibility checks for WP 5.3's new date functions.
* Standardize all date time usage so that content will drip using WordPress' timezone. 
* Reorganizes tests to conform with Sensei test structure.
* Using various timezones relative to UTC/PHP timezone, check to make sure both relative/dynamic drips and absolute drips happen at the correct date.

Use WordPress timezone when dripping lessons

---

changelog.txt
lang/sensei-content-drip.pot
package-lock.json
package.json
sensei-content-drip.php

Pre-built package: 
[sensei-content-drip.zip](https://github.com/woocommerce/sensei-content-drip/files/5629806/sensei-content-drip.zip)
This also includes our new build system, so we might want to just to a quick test for visual regressions.
* New: Adds partial French translations - #213
* Tweak: Use WordPress' timezone when dripping lessons - #214
* Fix: Minor display issue in WordPress admin on the lesson editor - #201

Release 2.1.0

---

includes/class-sensei-content-drip.php

Fixes issue reported in https://github.com/woocommerce/sensei-content-drip/issues/222#issuecomment-916726977
* The script enqueue check was broken in the past through this change in the core plugin: https://github.com/Automattic/sensei/commit/325481069b8e977f450bd5673a7c5d993d83346f. This just tweaks the `$hook` check making it work again.
* Create a course with a lesson.
* Set a content drip to the lesson.
* Enroll a user in the course.
* Go to wp-admin > Learner Management > Manage learners (in the course created)
* In the Manual Content Drip section, select the user and the lesson.
* Give access to the user.
* Select the user and the lesson again.
* Make sure now you see a button to remove the access.

Fix admin manual drip script enqueue
